version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: triplezerosports
      POSTGRES_USER: triplezerosports
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cms:
    build:
      context: .
      dockerfile: apps/cms/Dockerfile
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://triplezerosports:password@postgres:5432/triplezerosports
      PAYLOAD_SECRET: super-secret-key-for-development
      WEB_URL: http://localhost:3000
      WEBHOOK_SECRET: webhook-secret-for-development
      PORT: 3001
    depends_on:
      - postgres
    volumes:
      - ./apps/cms/media:/app/media

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      PAYLOAD_URL: http://cms:3001
      WEBHOOK_SECRET: webhook-secret-for-development
      NEXT_PUBLIC_SITE_URL: http://localhost:3000
    depends_on:
      - cms

volumes:
  postgres_data:
